package AutoVerify::CodeGen;
##############################################################################
# AutoVerify::CodeGen
#
# One pure function per generated file: takes the classified context hash,
# returns the exact SystemVerilog text as a string (no file I/O here - that's
# Generator.pm's job). Every heredoc below is copied verbatim from gen_tb.pl's
# print blocks; only the printing was replaced with string return, so output
# is byte-identical to the original script.
##############################################################################
use strict;
use warnings;
use Exporter 'import';

our @EXPORT_OK = qw(
    sig_decl field_decl
    gen_pkg gen_if gen_transaction gen_driver gen_monitor
    gen_scoreboard gen_env gen_tb_top gen_filelist
);

sub sig_decl {
    my ($p) = @_;
    my @bits = ($p->{type});
    push @bits, $p->{signed} if $p->{signed};
    push @bits, $p->{width}  if $p->{width};
    push @bits, $p->{name};
    return join(" ", @bits);
}

sub field_decl {
    my ($p, $rand) = @_;
    my @bits;
    push @bits, "rand" if $rand;
    push @bits, "logic";
    push @bits, $p->{signed} if $p->{signed};
    push @bits, $p->{width}  if $p->{width};
    push @bits, $p->{name};
    return join(" ", @bits);
}

# ===========================================================================
# 1. Package (parameters)
# ===========================================================================
sub gen_pkg {
    my (%c) = @_;
    my $module_name   = $c{module_name};
    my $param_order   = $c{param_order};
    my $param_default = $c{param_default};
    my $has_params    = $c{has_params};

    my $body = "";
    if ($has_params) {
        for my $name (@$param_order) {
            $body .= "  parameter $name = $param_default->{$name};\n";
        }
    } else {
        $body .= "  // No parameters detected on $module_name - file kept for symmetry.\n";
    }

    return <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// Parameters shared between the interface and the class-based environment.
package ${module_name}_pkg;

$body
endpackage : ${module_name}_pkg
SV
}

# ===========================================================================
# 2. Interface
# ===========================================================================
sub gen_if {
    my (%c) = @_;
    my $module_name  = $c{module_name};
    my $param_order  = $c{param_order};
    my $has_params   = $c{has_params};
    my $ports        = $c{ports};
    my $clk_port     = $c{clk_port};
    my $inout_ports  = $c{inout_ports};

    my $import_line = "  import ${module_name}_pkg::*;\n";

    my $param_port = "";
    if ($has_params) {
        my @lines = map { "  parameter $_ = ${module_name}_pkg::$_" } @$param_order;
        $param_port = "#(\n" . join(",\n", @lines) . "\n)\n";
    }

    my @all_non_clk = grep { !$clk_port || $_->{name} ne $clk_port } @$ports;
    my $signal_block = "";
    for my $p (@all_non_clk) {
        my @bits = ("logic");
        push @bits, $p->{signed} if $p->{signed};
        push @bits, $p->{width}  if $p->{width};
        push @bits, $p->{name} . ";";
        $signal_block .= "  " . join(" ", @bits) . "\n";
    }

    my @dut_in_names  = grep { $_ ne ($clk_port // '') } map { $_->{name} } grep { $_->{dir} eq 'input' } @$ports;
    my @dut_out_names = map { $_->{name} } grep { $_->{dir} eq 'output' } @$ports;
    my @dut_io_names  = map { $_->{name} } @$inout_ports;

    my $dut_modport = "  modport DUT (\n" .
        "    input  clk" . (@dut_in_names ? ", " . join(", ", @dut_in_names) : "") . "" .
        (@dut_io_names ? ",\n    inout  " . join(", ", @dut_io_names) : "") .
        (@dut_out_names ? ",\n    output " . join(", ", @dut_out_names) : "") . "\n" .
        "  );\n";

    my $tb_modport = "  modport TB (\n" .
        "    input  clk" . (@dut_out_names ? ", " . join(", ", @dut_out_names) : "") . "," .
        "\n    output " . join(", ", @dut_in_names ? @dut_in_names : ("/* no stimulus ports */")) .
        (@dut_io_names ? ",\n    inout  " . join(", ", @dut_io_names) : "") . "\n" .
        "  );\n";

    my $mon_modport = "  modport MON (\n" .
        "    input clk" . (@dut_in_names ? ", " . join(", ", @dut_in_names) : "") .
        (@dut_out_names ? ", " . join(", ", @dut_out_names) : "") .
        (@dut_io_names ? ", " . join(", ", @dut_io_names) : "") . "\n" .
        "  );\n";

    return <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// Bundles all DUT signals + directional modports for DUT / TB / passive monitor use.
$import_line
interface ${module_name}_if ${param_port}(
  input logic clk
);

$signal_block
$dut_modport
$tb_modport
$mon_modport
endinterface : ${module_name}_if
SV
}

# ===========================================================================
# 3. Transaction
# ===========================================================================
sub gen_transaction {
    my (%c) = @_;
    my $module_name = $c{module_name};
    my $has_params  = $c{has_params};
    my $stim_ports  = $c{stim_ports};
    my $resp_ports  = $c{resp_ports};

    my $import_line = $has_params ? "  import ${module_name}_pkg::*;\n" : "";

    my $stim_fields = join("\n", map { "  " . field_decl($_, 1) . ";" } @$stim_ports);
    my $resp_fields = join("\n", map { "  " . field_decl($_, 0) . ";" } @$resp_ports);
    $stim_fields = "  // (no non-clock/reset input ports found)" unless @$stim_ports;
    $resp_fields = "  // (no output ports found)" unless @$resp_ports;

    my $display_stim = join(", ", map { "$_->{name}=%0h" } @$stim_ports);
    my $display_stim_args = join(", ", map { $_->{name} } @$stim_ports);
    my $display_resp = join(", ", map { "$_->{name}=%0h" } @$resp_ports);
    my $display_resp_args = join(", ", map { $_->{name} } @$resp_ports);

    my $display_fmt  = "[%s] " . $display_stim . ($display_resp ? ($display_stim ? " | " : "") . $display_resp : "");
    my $display_args = join(", ", grep { length($_) } ("tag", $display_stim_args, $display_resp_args));

    my $out = <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// One randomizable stimulus item. Driver fills the rand (stimulus) fields;
// Monitor fills the plain (response) fields after sampling the DUT outputs.
$import_line
class ${module_name}_transaction;

  // ---- stimulus (randomized by the driver's generator loop) ----
$stim_fields

  // ---- response (filled in by the monitor after sampling) ----
$resp_fields

  // Add SystemVerilog constraint blocks here to bias / restrict random
  // stimulus, e.g.:
  //   constraint c_reasonable { data_in inside {[0:255]}; }

  function void display(string tag = "TXN");
    \$display("$display_fmt", $display_args);
  endfunction

  function ${module_name}_transaction copy();
    copy = new();
    copy.copy_fields(this);
  endfunction

  function void copy_fields(${module_name}_transaction t);
SV
    for my $p (@$stim_ports) {
        $out .= "    this.$p->{name} = t.$p->{name};\n";
    }
    for my $p (@$resp_ports) {
        $out .= "    this.$p->{name} = t.$p->{name};\n";
    }
    $out .= <<SV;
  endfunction

endclass : ${module_name}_transaction
SV
    return $out;
}

# ===========================================================================
# 4. Driver
# ===========================================================================
sub gen_driver {
    my (%c) = @_;
    my $module_name    = $c{module_name};
    my $has_params     = $c{has_params};
    my $stim_ports     = $c{stim_ports};
    my $rst_port       = $c{rst_port};
    my $rst_active_low = $c{rst_active_low};

    my $import_line = $has_params ? "  import ${module_name}_pkg::*;\n" : "";

    my $drive_lines = join("\n", map { "    vif.$_->{name} <= txn.$_->{name};" } @$stim_ports);
    $drive_lines = "    // no stimulus ports to drive" unless @$stim_ports;

    my $idle_lines = join("\n", map { "    vif.$_->{name} <= '0;" } @$stim_ports);
    $idle_lines = "    // nothing to idle" unless @$stim_ports;

    my $reset_block;
    if ($rst_port) {
        my $assert_val   = $rst_active_low ? "1'b0" : "1'b1";
        my $deassert_val = $rst_active_low ? "1'b1" : "1'b0";
        $reset_block = <<SV;
  // Pulses the DUT's reset for reset_cycles clock periods.
  task automatic do_reset(int reset_cycles = 5);
    vif.$rst_port <= $assert_val;
$idle_lines
    repeat (reset_cycles) \@(posedge vif.clk);
    vif.$rst_port <= $deassert_val;
    \@(posedge vif.clk);
    \$display("[DRIVER] Reset de-asserted after %0d cycles", reset_cycles);
  endtask
SV
    } else {
        $reset_block = <<SV;
  // No reset port was detected on $module_name - nothing to pulse.
  task automatic do_reset(int reset_cycles = 5);
$idle_lines
    repeat (reset_cycles) \@(posedge vif.clk);
  endtask
SV
    }

    return <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// Pulls transactions off gen2drv and drives them onto the interface every
// clock edge. Owns the reset sequence.
$import_line
class ${module_name}_driver;

  virtual ${module_name}_if.TB vif;
  mailbox #(${module_name}_transaction) gen2drv;

  function new(virtual ${module_name}_if.TB vif, mailbox #(${module_name}_transaction) gen2drv);
    this.vif    = vif;
    this.gen2drv = gen2drv;
  endfunction

$reset_block

  task automatic run();
    ${module_name}_transaction txn;
    forever begin
      gen2drv.get(txn);
      \@(posedge vif.clk);
$drive_lines
    end
  endtask

endclass : ${module_name}_driver
SV
}

# ===========================================================================
# 5. Monitor
# ===========================================================================
sub gen_monitor {
    my (%c) = @_;
    my $module_name = $c{module_name};
    my $has_params  = $c{has_params};
    my $stim_ports  = $c{stim_ports};
    my $resp_ports  = $c{resp_ports};

    my $import_line = $has_params ? "  import ${module_name}_pkg::*;\n" : "";

    my $sample_stim = join("\n", map { "    txn.$_->{name} = vif.$_->{name};" } @$stim_ports);
    my $sample_resp = join("\n", map { "    txn.$_->{name} = vif.$_->{name};" } @$resp_ports);
    $sample_stim = "    // no stimulus ports to sample" unless @$stim_ports;
    $sample_resp = "    // no response ports to sample" unless @$resp_ports;

    return <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// Passively samples every port on the interface each clock and forwards a
// fully-populated transaction to the scoreboard.
$import_line
class ${module_name}_monitor;

  virtual ${module_name}_if.MON vif;
  mailbox #(${module_name}_transaction) mon2scb;

  function new(virtual ${module_name}_if.MON vif, mailbox #(${module_name}_transaction) mon2scb);
    this.vif     = vif;
    this.mon2scb = mon2scb;
  endfunction

  task automatic run();
    ${module_name}_transaction txn;
    forever begin
      \@(posedge vif.clk);
      txn = new();
$sample_stim
$sample_resp
      mon2scb.put(txn);
    end
  endtask

endclass : ${module_name}_monitor
SV
}

# ===========================================================================
# 6. Scoreboard
# ===========================================================================
sub gen_scoreboard {
    my (%c) = @_;
    my $module_name = $c{module_name};
    my $has_params  = $c{has_params};

    my $import_line = $has_params ? "  import ${module_name}_pkg::*;\n" : "";

    return <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// Receives sampled transactions and checks them. Replace check_result()
// with a real reference model for $module_name.
$import_line
class ${module_name}_scoreboard;

  mailbox #(${module_name}_transaction) mon2scb;
  int unsigned num_checked;
  int unsigned num_errors;

  function new(mailbox #(${module_name}_transaction) mon2scb);
    this.mon2scb    = mon2scb;
    this.num_checked = 0;
    this.num_errors  = 0;
  endfunction

  // TODO: replace with a real golden model for $module_name.
  // Return 1 if txn's response fields are correct given its stimulus fields.
  function automatic bit check_result(${module_name}_transaction txn);
    return 1; // stub: always passes until a reference model is added
  endfunction

  task automatic run();
    ${module_name}_transaction txn;
    forever begin
      mon2scb.get(txn);
      num_checked++;
      if (!check_result(txn)) begin
        num_errors++;
        txn.display(\$sformatf("SCB-FAIL #%0d", num_checked));
      end
    end
  endtask

  function void report();
    \$display("[SCOREBOARD] checked=%0d errors=%0d", num_checked, num_errors);
  endfunction

endclass : ${module_name}_scoreboard
SV
}

# ===========================================================================
# 7. Environment
# ===========================================================================
sub gen_env {
    my (%c) = @_;
    my $module_name = $c{module_name};
    my $has_params  = $c{has_params};
    my $num_txns    = $c{num_txns};

    my $import_line = $has_params ? "  import ${module_name}_pkg::*;\n" : "";

    return <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// Wires driver + monitor + scoreboard together and runs the random
// stimulus loop.
$import_line
class ${module_name}_env;

  virtual ${module_name}_if vif;

  ${module_name}_driver     drv;
  ${module_name}_monitor    mon;
  ${module_name}_scoreboard scb;

  mailbox #(${module_name}_transaction) gen2drv;
  mailbox #(${module_name}_transaction) mon2scb;

  function new(virtual ${module_name}_if vif);
    this.vif    = vif;
    gen2drv     = new();
    mon2scb     = new();
    drv         = new(vif.TB, gen2drv);
    mon         = new(vif.MON, mon2scb);
    scb         = new(mon2scb);
  endfunction

  task automatic run(int num_txns = $num_txns);
    ${module_name}_transaction txn;

    fork
      drv.run();
      mon.run();
      scb.run();
    join_none

    drv.do_reset();

    \$display("[ENV] Generating %0d random transactions...", num_txns);
    for (int i = 0; i < num_txns; i++) begin
      txn = new();
      if (!txn.randomize())
        \$fatal(1, "[ENV] randomize() failed on transaction %0d", i);
      gen2drv.put(txn);
    end

    // let the pipeline drain before wrapping up
    repeat (10) \@(posedge vif.clk);
    scb.report();
  endtask

endclass : ${module_name}_env
SV
}

# ===========================================================================
# 8. Top-level testbench module
# ===========================================================================
sub gen_tb_top {
    my (%c) = @_;
    my $module_name  = $c{module_name};
    my $has_params   = $c{has_params};
    my $param_order  = $c{param_order};
    my $ports        = $c{ports};
    my $clk_port     = $c{clk_port};
    my $num_txns     = $c{num_txns};

    my @port_conn;
    for my $p (@$ports) {
        push @port_conn, "    .$p->{name}(dut_if.$p->{name})";
    }
    my $port_conn_str = join(",\n", @port_conn);

    my $param_override = "";
    if ($has_params) {
        my @lines = map { ".$_(${module_name}_pkg::$_)" } @$param_order;
        $param_override = " #(" . join(", ", @lines) . ")";
    }

    my $clk_decl = $clk_port
        ? "  logic $clk_port = 0;\n  always #5 $clk_port = ~$clk_port; // 100MHz"
        : "  // WARNING: no clock port detected - add one manually with --clk=<name>\n  logic clk = 0;\n  always #5 clk = ~clk;";
    my $clk_conn = $clk_port // "clk";

    my $out = <<SV;
// Auto-generated by HDL Testbench Generator - do not hand edit lightly.
// Top-level: generates clock, instantiates the interface + DUT, and kicks
// off the class-based environment.
`timescale 1ns/1ps
SV
    $out .= ($has_params ? "import ${module_name}_pkg::*;\n" : "");
    $out .= <<SV;

module ${module_name}_tb_top;

$clk_decl

  ${module_name}_if${param_override} dut_if (.clk($clk_conn));

  $module_name dut (
$port_conn_str
  );

  ${module_name}_env env;

  initial begin
    env = new(dut_if);
    env.run($num_txns);
    #100;
    \$display("[TB] Simulation complete.");
    \$finish;
  end

  initial begin
    \$dumpfile("${module_name}_tb.vcd");
    \$dumpvars(0, ${module_name}_tb_top);
  end

endmodule : ${module_name}_tb_top
SV
    return $out;
}

# ===========================================================================
# 9. Filelist
# ===========================================================================
sub gen_filelist {
    my (%c) = @_;
    my $module_name = $c{module_name};
    my $has_params  = $c{has_params};

    my $out = "// Auto-generated compile order for $module_name\n";
    $out .= "${module_name}_pkg.sv\n" if $has_params;
    for my $f (qw(if transaction driver monitor scoreboard env tb_top)) {
        $out .= "${module_name}_${f}.sv\n";
    }
    return $out;
}

1;
